### ISSUE TITLE
pls release

### ISSUE THREAD

**Issue by hannesm** [verbosemode/syslog-message#12]
think we should have a release from master... https://tools.ietf.org/html/rfc5424 support can wait for next release

**Comment by hannesm** [comment]
you should update the release date in CHANGES.md for 0.0.2 (it is `"now"` atm)

**Comment by verbosemode** [comment]
Thanks for the hint. I'll also need to fix the README to play nice with Topkg, when building the description for the OPAM repo.

**Comment by hannesm** [comment]
thx!
