### ISSUE TITLE
MSG isn't validated

### ISSUE THREAD

**Issue by dra27** [verbosemode/syslog-message#18]
[RFC3164 4.1.3](https://tools.ietf.org/html/rfc3164#section-4.1.3) describes the two fields of the `MSG` portion, but this isn't validated anywhere. In principle, the `encode` function should probably raise if there is no discernable alphanumeric `TAG` of 32 chars or fewer delimited by a non-alphanumeric character in `message`.

**Comment by verbosemode** [comment]
We could also replace the message field in type t by a tuple, record or even a new type to accommodate for the tag and content field. This would break the API, but afaik the only consumer of this library is logs-syslog at the moment. If @hannesm is fine with it, this might be an option to raising an exception.

**Comment by Leonidas-from-XIV** [comment]
I think this would be preferable, since exceptions tend to be rather surprising and break your code on runtime. The other possibility is to use the `result` type with polymorphic variants, I've also made good experiences with that.

**Comment by hannesm** [comment]
I'm happy with a (breaking) API change :)
FWIW: I like to use the `result` type for `decode` style functions (i.e. input from the network), but `encode` (i.e. input from trusted source, such as hardcoded parameters) I'm happy with `Invalid_argument` exceptions.

and I don't expect that this `tag` comes dynamically from untrusted sources..

**Comment by hannesm** [comment]
see #20
