### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by vbmithr** [verbosemode/syslog-message#24]

**Comment by verbosemode** [comment]
Sure. I'll do it tomorrow, so you can get rid of your pins.

**Comment by verbosemode** [comment]
I'll have to postpone it until the weekend. sorry.

**Comment by vbmithr** [comment]
No worries :D

**Comment by verbosemode** [comment]
The 1.1.0 release with your changes is now on its way: https://github.com/ocaml/opam-repository/pull/13961
