### ISSUE TITLE
Switch from Travis to OCaml-CI

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [verbosemode/syslog-message#26]
Since Travis is more-or-less effectively dead it would be nice to switch to [OCaml CI](https://github.com/ocurrent/ocaml-ci) to get this project to build and see PRs get exercised by builders again. What do you think @verbosemode?

**Comment by verbosemode** [comment]
That's a great idea. I've already enabled the app for the repo and I'm reading through the instructions now. As soon as it it setup we can get rid of the travis config.

**Comment by Leonidas-from-XIV** [comment]
Great! Let me know if you need any help, I was able to successfully set it up for my system recently.

Relevant PR: https://github.com/ocurrent/ocaml-ci/pull/386

**Comment by verbosemode** [comment]
OCaml-CI has been enabled for the repository now. The change is included in PR #27

**Comment by verbosemode** [comment]
Thanks again for the suggestion and sorry for the delay. I've finally merged the PR :-)
