### ISSUE TITLE
Idea on refactor

### ISSUE THREAD

**Issue by fxfactorial** [verbosemode/syslog-message#7]
It seems to me that this would be a good usage of mehrir instead of a hand rolled parser.

**Comment by hannesm** [comment]
not sure whether I agree, it is not much parser code here, and introducing a menhir dependency is rather heavy-weight imho.  it is worth to have a hand rolled and menhir based solution side-by-side for comparison...

**Comment by Leonidas-from-XIV** [comment]
I would even disagree, since creating a grammar for such a simple format with a cannon like mehir seems a bit like overkill. If we had something like Attoparsec which would be concise, that'd be neat, but no canonical parser combinator for OCaml has surfaced so far.

**Comment by hannesm** [comment]
@Leonidas-from-XIV maybe https://github.com/inhabitedtype/angstrom/ ?

**Comment by fxfactorial** [comment]
Okay, its clear this is a silly idea. Thanks all!

**Comment by wiredsister** [comment]
@fxfactorial I don't think it's silly to standardize on a parser, but I agree menhir is overkill. Angstrom seems interesting @hannesm. I'm going to reopen this as a feature request, but maybe it's worth noting it's low on the priority list.
